[package]
name = "haprs"
version = "0.1.0"
authors = ["Mat Trudel <mat@geeky.net>"]
edition = "2018"

[dependencies]
env_logger = "0.8"
libmdns = "0.5"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
