[package]
name = "haprs"
version = "0.1.0"
authors = ["Mat Trudel <mat@geeky.net>"]
edition = "2018"

[dependencies]
env_logger = "0.8"
libmdns = "0.5"
tide = "0.14.0"
async-std = { version = "1.6.0", features = ["attributes"] }
futures = "0.3"
